#!/usr/bin/env python3
"""
generate_index.py — Rebuild vault-wide index and dashboard notes.

Rebuilds:
  - citadel/_index.md — vault-wide overview
  - citadel/market/_dashboard.md — recent reports, active watchlist
  - citadel/literature/_catalog.md — paper catalog from manifest

Usage:
  python3 knowledge-maester/scripts/generate_index.py \\
    [--vault-path PATH] \\
    [--paper-bank-path PATH]
"""
import argparse
import json
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import vault_io


def _count_notes_in(vault_path: Path, rel_dir: str) -> int:
    d = vault_path / rel_dir
    if not d.exists():
        return 0
    return sum(1 for f in d.glob("*.md") if not f.stem.startswith("_"))


def generate_vault_index(vault_path: Path) -> str:
    today = vault_io.today_str()

    # Count notes per section
    counts = {
        "reports": _count_notes_in(vault_path, "market/reports"),
        "tickers": _count_notes_in(vault_path, "market/tickers"),
        "analysis": _count_notes_in(vault_path, "market/analysis"),
        "archive": _count_notes_in(vault_path, "market/archive"),
        "papers": _count_notes_in(vault_path, "literature/papers"),
        "digests": _count_notes_in(vault_path, "literature/digests"),
        "fields": _count_notes_in(vault_path, "literature/fields"),
        "surveys": _count_notes_in(vault_path, "literature/surveys"),
    }

    content = f"""---
type: index
title: Citadel Vault Index
date: {today}
last_updated: {today}
---

# Citadel

Research and market intelligence vault.

*Last updated: {today}*

## Sections

### Market Intelligence
- [[market/reports/]] — {counts['reports']} reports
- [[market/tickers/]] — {counts['tickers']} ticker notes
- [[market/analysis/]] — {counts['analysis']} analyses
- [[market/archive/]] — {counts['archive']} archived notes

### Literature
- [[literature/papers/]] — {counts['papers']} papers
- [[literature/digests/]] — {counts['digests']} digests
- [[literature/fields/]] — {counts['fields']} field summaries
- [[literature/surveys/]] — {counts['surveys']} surveys

### Reference
- [[reference/]] — Reference material
- [[templates/]] — Note templates
- [[zotero/]] — Zotero-synced references

## Dashboards
- [[market/_dashboard]] — Market activity dashboard
- [[literature/_catalog]] — Paper catalog

## Stats
| Category | Count |
|---|---|
| Market reports | {counts['reports']} |
| Ticker notes | {counts['tickers']} |
| Analyses | {counts['analysis']} |
| Papers | {counts['papers']} |
| Digests | {counts['digests']} |
"""
    return content


def generate_market_dashboard(vault_path: Path) -> str:
    today_str = vault_io.today_str()
    today = date.today()

    # Gather recent reports (last 30 days)
    reports_dir = vault_path / "market" / "reports"
    recent_reports = []
    all_watchlist = {}  # symbol -> count

    if reports_dir.exists():
        for md_file in sorted(reports_dir.glob("*.md"), reverse=True):
            if md_file.stem.startswith("_"):
                continue
            content = md_file.read_text(encoding="utf-8", errors="replace")
            fm, _ = vault_io.parse_frontmatter(content)
            report_date = vault_io.parse_iso_date(fm.get("date", ""))
            if report_date and (today - report_date).days <= 30:
                recent_reports.append((md_file.stem, fm))
            # Accumulate watchlist
            wl = fm.get("watchlist", [])
            if isinstance(wl, list):
                for s in wl:
                    all_watchlist[s] = all_watchlist.get(s, 0) + 1

    # Recent reports table
    reports_rows = []
    for slug, fm in recent_reports[:10]:
        title = fm.get("title", slug)
        report_date = fm.get("date", "")
        confidence = fm.get("confidence", "")
        wl = fm.get("watchlist", [])
        wl_str = ", ".join(wl[:4]) + ("..." if len(wl) > 4 else "") if wl else ""
        reports_rows.append(f"| [[{slug}\\|{title[:40]}]] | {report_date} | {confidence} | {wl_str} |")

    reports_table = "\n".join(reports_rows) if reports_rows else "| *No recent reports* | | | |"

    # Active watchlist (sorted by frequency)
    watchlist_sorted = sorted(all_watchlist.items(), key=lambda x: -x[1])[:20]
    watchlist_rows = [f"| [[{sym}]] | {cnt} |" for sym, cnt in watchlist_sorted]
    watchlist_table = "\n".join(watchlist_rows) if watchlist_rows else "| *No tickers tracked* | |"

    content = f"""---
type: memory
title: Market Dashboard
date: {today_str}
last_updated: {today_str}
tags: [dashboard, market]
category: dashboard
status: active
---

# Market Dashboard

*Auto-generated by knowledge-maester on {today_str}*

> Use Dataview plugin for live queries. This file provides a static snapshot.

## Recent Reports (last 30 days)

| Report | Date | Confidence | Watchlist |
|---|---|---|---|
{reports_table}

## Active Watchlist

| Ticker | Report Count |
|---|---|
{watchlist_table}

## Sector Activity

```dataview
TABLE date, confidence, watchlist
FROM "market/reports"
WHERE status = "active"
SORT date DESC
LIMIT 20
```

## Analysis Queue

```dataview
TABLE date, confidence
FROM "market/analysis"
WHERE status = "draft"
SORT date DESC
```
"""
    return content


def generate_literature_catalog(vault_path: Path, paper_bank_path: Path) -> str:
    today_str = vault_io.today_str()

    # Load manifest
    manifest = vault_io.read_manifest(paper_bank_path)
    manifest_by_key = {e.get("cite_key"): e for e in manifest if e.get("cite_key")}

    # Gather all paper notes
    papers_dir = vault_path / "literature" / "papers"
    paper_rows = []
    if papers_dir.exists():
        for md_file in sorted(papers_dir.glob("*.md")):
            if md_file.stem.startswith("_"):
                continue
            content = md_file.read_text(encoding="utf-8", errors="replace")
            fm, body = vault_io.parse_frontmatter(content)
            cite_key = fm.get("cite_key", md_file.stem)
            title = fm.get("title", cite_key)
            year = fm.get("year", "")
            authors = fm.get("authors", [])
            if isinstance(authors, list):
                author_str = authors[0] if authors else ""
                if len(authors) > 1:
                    author_str += " et al."
            else:
                author_str = str(authors)
            review_status = fm.get("review_status", "draft")
            # Check if digest exists
            digest_exists = (vault_path / "literature" / "digests" / f"{cite_key}-digest.md").exists()
            digest_link = f"[[{cite_key}-digest|D]]" if digest_exists else ""
            paper_rows.append(
                f"| [[{cite_key}\\|{title[:45]}]] | {author_str} | {year} | "
                f"{review_status} | {digest_link} |"
            )

    papers_table = "\n".join(paper_rows) if paper_rows else "| *No papers yet* | | | | |"

    content = f"""---
type: memory
title: Literature Catalog
date: {today_str}
last_updated: {today_str}
tags: [catalog, literature]
category: catalog
status: active
---

# Literature Catalog

*Auto-generated by knowledge-maester on {today_str}*

## Papers ({len(paper_rows)} total)

| Title | First Author | Year | Status | Digest |
|---|---|---|---|---|
{papers_table}

## Paper Bank Stats

- Manifest entries: {len(manifest)}
- Vault paper notes: {len(paper_rows)}

## Digests

```dataview
TABLE field, date
FROM "literature/digests"
SORT date DESC
```

## Fields

```dataview
TABLE date
FROM "literature/fields"
SORT title ASC
```
"""
    return content


def main():
    parser = argparse.ArgumentParser(description="Rebuild vault index and dashboard notes")
    parser.add_argument("--vault-path", default=str(vault_io.DEFAULT_VAULT_PATH))
    parser.add_argument("--paper-bank-path", default=str(vault_io.DEFAULT_PAPER_BANK_PATH))
    args = parser.parse_args()

    vault_path = Path(args.vault_path).expanduser()
    paper_bank_path = Path(args.paper_bank_path).expanduser()

    if not vault_path.exists():
        print(f"ERROR: Vault not found at {vault_path}")
        sys.exit(1)

    # Generate and write _index.md
    index_content = generate_vault_index(vault_path)
    index_path = vault_path / "_index.md"
    index_path.write_text(index_content, encoding="utf-8")
    print(f"WRITTEN: _index.md")

    # Generate and write market/_dashboard.md
    dashboard_content = generate_market_dashboard(vault_path)
    dashboard_path = vault_path / "market" / "_dashboard.md"
    dashboard_path.write_text(dashboard_content, encoding="utf-8")
    print(f"WRITTEN: market/_dashboard.md")

    # Generate and write literature/_catalog.md
    catalog_content = generate_literature_catalog(vault_path, paper_bank_path)
    catalog_path = vault_path / "literature" / "_catalog.md"
    catalog_path.write_text(catalog_content, encoding="utf-8")
    print(f"WRITTEN: literature/_catalog.md")

    print("DONE: Vault indexes rebuilt.")


if __name__ == "__main__":
    main()
