#!/usr/bin/env python3
"""
polish_note.py — Update an existing vault note with new information.

Merges new content into the note while preserving human-authored sections
(any content outside <!-- AUTO-GENERATED --> markers).

Usage:
  python3 knowledge-maester/scripts/polish_note.py \\
    --note-path VAULT_RELATIVE_PATH \\
    --update PATH_TO_UPDATE_MD \\
    [--vault-path PATH]
"""
import argparse
import re
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import vault_io


def polish_note(note_rel_path: str, update_path: Path, vault_path: Path) -> dict:
    """
    Merge update into existing vault note.
    Returns result dict with 'status' and 'changes'.
    """
    abs_note_path = vault_path / note_rel_path
    if not abs_note_path.exists():
        raise FileNotFoundError(f"Note not found: {abs_note_path}")

    # Read existing note
    existing_content = abs_note_path.read_text(encoding="utf-8")
    existing_fm, existing_body = vault_io.parse_frontmatter(existing_content)

    # Read update artifact
    update_content = update_path.read_text(encoding="utf-8")
    update_fm, update_body = vault_io.parse_frontmatter(update_content)

    today = vault_io.today_str()
    changes = []

    # --- Update frontmatter ---
    # Only update fields that are explicitly provided in update frontmatter
    # and are safe to overwrite (not title, date, cite_key)
    SAFE_UPDATE_FIELDS = {"tags", "confidence", "sources_count", "review_status",
                          "content_status", "related_tickers", "related_reports",
                          "watchlist", "status"}
    for field in SAFE_UPDATE_FIELDS:
        if field in update_fm:
            old_val = existing_fm.get(field)
            new_val = update_fm[field]
            # Merge lists rather than overwrite
            if isinstance(old_val, list) and isinstance(new_val, list):
                merged = list(dict.fromkeys(old_val + new_val))
                if merged != old_val:
                    existing_fm[field] = merged
                    changes.append(f"merged list field: {field}")
            elif old_val != new_val:
                existing_fm[field] = new_val
                changes.append(f"updated field: {field} ({old_val!r} → {new_val!r})")

    # Always update last_updated
    existing_fm["last_updated"] = today

    # Increment sources_count if update provides new sources
    update_sources = update_fm.get("sources_count", 0)
    if update_sources:
        try:
            existing_fm["sources_count"] = int(existing_fm.get("sources_count", 0)) + int(update_sources)
            changes.append(f"incremented sources_count by {update_sources}")
        except (ValueError, TypeError):
            pass

    # --- Merge body content ---
    # Sections to append to (not overwrite) from update
    APPENDABLE_SECTIONS = ["Key Findings", "Analysis", "Links", "Notes", "Open Questions", "Predictions"]

    new_body = existing_body

    for section_name in APPENDABLE_SECTIONS:
        update_section = _extract_section(update_body, section_name)
        if not update_section:
            continue
        existing_section = _extract_section(existing_body, section_name)
        # Append if not already present
        if update_section not in existing_body:
            if _section_exists(new_body, section_name):
                new_body = _append_to_section(new_body, section_name, update_section)
                changes.append(f"appended to section: {section_name}")
            else:
                # Add new section at end
                new_body = new_body.rstrip() + f"\n\n## {section_name}\n\n{update_section}\n"
                changes.append(f"added new section: {section_name}")

    # --- Update AUTO-GENERATED sections if update has them ---
    auto_pattern = re.compile(
        r"<!-- AUTO-GENERATED -->(.+?)<!-- /AUTO-GENERATED -->",
        re.DOTALL
    )
    update_auto = auto_pattern.search(update_body)
    if update_auto:
        new_content = vault_io.update_autogenerated_section(
            new_body, update_auto.group(1).strip()
        )
        if new_content != new_body:
            new_body = new_content
            changes.append("updated AUTO-GENERATED section")

    if not changes:
        print(f"NO_CHANGES: {note_rel_path}")
        return {"status": "no_changes", "changes": []}

    # Write updated note
    vault_io.write_note(vault_path, note_rel_path, existing_fm, new_body)
    print(f"POLISHED: {note_rel_path} ({len(changes)} change(s))")
    for c in changes:
        print(f"  - {c}")

    return {"status": "polished", "changes": changes}


def _extract_section(body: str, heading: str) -> str:
    pattern = re.compile(
        r"^#{1,3}\s+" + re.escape(heading) + r"\s*$",
        re.MULTILINE | re.IGNORECASE
    )
    m = pattern.search(body)
    if not m:
        return ""
    start = m.end()
    next_heading = re.search(r"^#{1,2}\s+", body[start:], re.MULTILINE)
    end = start + next_heading.start() if next_heading else len(body)
    return body[start:end].strip()


def _section_exists(body: str, heading: str) -> bool:
    pattern = re.compile(
        r"^#{1,3}\s+" + re.escape(heading) + r"\s*$",
        re.MULTILINE | re.IGNORECASE
    )
    return bool(pattern.search(body))


def _append_to_section(body: str, heading: str, new_content: str) -> str:
    """Append new_content at the end of the named section."""
    pattern = re.compile(
        r"(^#{1,3}\s+)" + re.escape(heading) + r"(\s*$)(.*?)(?=^#{1,3}\s+|\Z)",
        re.MULTILINE | re.IGNORECASE | re.DOTALL
    )
    def replacer(m):
        heading_prefix = m.group(1) + heading + m.group(2)
        existing_section_content = m.group(3).rstrip()
        return f"{heading_prefix}{existing_section_content}\n\n{new_content}\n\n"
    return pattern.sub(replacer, body)


def main():
    parser = argparse.ArgumentParser(description="Polish an existing vault note with new information")
    parser.add_argument("--note-path", required=True, help="Vault-relative path to the note")
    parser.add_argument("--update", required=True, help="Path to update markdown file")
    parser.add_argument("--vault-path", default=str(vault_io.DEFAULT_VAULT_PATH))
    args = parser.parse_args()

    update_path = Path(args.update).expanduser().resolve()
    vault_path = Path(args.vault_path).expanduser()

    if not update_path.exists():
        print(f"ERROR: Update file not found: {update_path}")
        sys.exit(1)
    if not vault_path.exists():
        print(f"ERROR: Vault not found at {vault_path}")
        sys.exit(1)

    result = polish_note(args.note_path, update_path, vault_path)
    print(f"DONE: status={result['status']}")


if __name__ == "__main__":
    main()
